---
version: "2"
plugins:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-81
exclude_patterns:
- dist/
- "**/test/"
