image: ruby:2.6.5
stages:
  - test
  - deploy
include:
  - template: Code-Quality.gitlab-ci.yml

minitest:
  stage: test
  script:
    - bundle install
    - rake test
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - minitest
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
