image: ruby:alpine
stages:
  - test
  - deploy
include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

minitest:
  stage: test
  script:
    - apk update
    - apk add --no-cache build-base
    - gem update --system
    - gem install bundler --version=2.1.4
    - bundle install
    - bundle exec rake test
  artifacts:
    paths:
      - tmp/coverage

pages:
  stage: deploy
  dependencies:
    - minitest
  script:
    - mv tmp/coverage public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
